package solarex.ui.components;

import java.awt.Component;
import solarex.ui.UiHelper;
import solarex.ui.ComponentFactory;
import solarex.ui.FontFactory;

/**
 *
 * @author Hj. Malthaner
 */
public class DonationPanel extends javax.swing.JPanel
{
    public int donation;
    
    /**
     * Creates new form DonationPanel
     */
    public DonationPanel()
    {
        initComponents();
        
        ComponentFactory.customizeButton(donationButton);
        
        jLabel1.setFont(FontFactory.getLarger());
        jLabel2.setFont(FontFactory.getLarger());
        donationInputField.setFont(FontFactory.getLarger());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        donationInputField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        donationButton = new javax.swing.JButton();

        setBackground(java.awt.Color.darkGray);
        setPreferredSize(new java.awt.Dimension(320, 140));
        setLayout(null);

        jLabel1.setForeground(java.awt.Color.orange);
        jLabel1.setText("How much do you want to donate?");
        add(jLabel1);
        jLabel1.setBounds(20, 10, 270, 30);

        donationInputField.setBackground(java.awt.Color.black);
        donationInputField.setForeground(java.awt.Color.white);
        donationInputField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        donationInputField.setText("10");
        donationInputField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                donationInputFieldActionPerformed(evt);
            }
        });
        add(donationInputField);
        donationInputField.setBounds(50, 50, 70, 22);

        jLabel2.setForeground(java.awt.Color.orange);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cr");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setPreferredSize(new java.awt.Dimension(320, 140));
        add(jLabel2);
        jLabel2.setBounds(120, 50, 20, 20);

        donationButton.setText("Donate!");
        donationButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                donationButtonActionPerformed(evt);
            }
        });
        add(donationButton);
        donationButton.setBounds(20, 90, 79, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void donationInputFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_donationInputFieldActionPerformed
    {//GEN-HEADEREND:event_donationInputFieldActionPerformed
        donationButtonActionPerformed(evt);
    }//GEN-LAST:event_donationInputFieldActionPerformed

    private void donationButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_donationButtonActionPerformed
    {//GEN-HEADEREND:event_donationButtonActionPerformed
        donation = Integer.parseInt(donationInputField.getText());
        
        Component component = UiHelper.findRootDialog(this);
        component.setVisible(false);
    }//GEN-LAST:event_donationButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton donationButton;
    private javax.swing.JTextField donationInputField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
