package solarex.ui.components;

import java.util.List;
import solarex.galaxy.Galaxy;
import solarex.galaxy.SystemLocation;
import solarex.ship.components.EquipmentFactory;
import solarex.ship.components.ShipComponent;
import solarex.system.Solar;
import solarex.util.RandomHelper;

/**
 *
 * @author Hj. Malthaner
 */
public class NewspaperPanel extends ImagedPanel
{

    /**
     * Creates new form NewspaperPanel
     */
    public NewspaperPanel()
    {
        initComponents();
        jScrollPane1.getViewport().setOpaque(false);
    }

    public void setDateTime(String s)
    {
        dateTimeLabel.setText(s);
    }
            
    
    public void setHeadline(int index, String headline)
    {
        switch(index)
        {
            case 1:        
                leadNewsHeadline.setText(headline);
                break;
            case 2:        
                headline2.setText(headline);
                break;
            case 3:        
                headline3.setText(headline);
                break;
            case 4:        
                headline4.setText(headline);
                break;
            case 5:        
                headline5.setText(headline);
                break;
        }
    }
    
    public void setNews(int index, String news)
    {
        switch(index)
        {
            case 1:        
                leadNewsLabel.setText(news);
                break;
            case 2:        
                news2.setText(news);
                break;
            case 3:        
                news3.setText(news);
                break;
            case 4:        
                news4.setText(news);
                break;
            case 5:        
                news5.setText(news);
                break;
        }
    }

    public void setHeadline2(String headline)
    {
        headline2.setText(headline);
    }
    
    public void setNews2(String news)
    {
        news2.setText(news);
    }
    
    public void setHeadline3(String headline)
    {
        headline3.setText(headline);
    }
    
    public void setNews3(String news)
    {
        news3.setText(news);
    }

    public void setColumnHeadline(String headline)
    {
        columnHeadline.setText(headline);
    }

    public void setColumnText(String news)
    {
        columnLabel.setText(news);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        pagePanel = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        leadNewsLabel = new javax.swing.JLabel();
        columnLabel = new javax.swing.JLabel();
        columnHeadline = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        news2 = new javax.swing.JLabel();
        headline2 = new javax.swing.JLabel();
        leadNewsHeadline = new javax.swing.JLabel();
        headline3 = new javax.swing.JLabel();
        news3 = new javax.swing.JLabel();
        headline4 = new javax.swing.JLabel();
        headline5 = new javax.swing.JLabel();
        news4 = new javax.swing.JLabel();
        news5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateTimeLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 153));
        setPreferredSize(new java.awt.Dimension(800, 592));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(0, 255, 0));
        jScrollPane1.setOpaque(false);

        pagePanel.setBackground(new java.awt.Color(51, 51, 255));
        pagePanel.setOpaque(false);
        pagePanel.setPreferredSize(new java.awt.Dimension(776, 500));
        pagePanel.setLayout(null);

        headingLabel.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(0, 0, 1));
        headingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel.setText("The Secret Eye");
        pagePanel.add(headingLabel);
        headingLabel.setBounds(80, 10, 600, 70);

        leadNewsLabel.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        leadNewsLabel.setForeground(new java.awt.Color(0, 0, 1));
        leadNewsLabel.setText("Text");
        leadNewsLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pagePanel.add(leadNewsLabel);
        leadNewsLabel.setBounds(10, 150, 370, 180);

        columnLabel.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        columnLabel.setForeground(new java.awt.Color(0, 0, 1));
        columnLabel.setText("text");
        columnLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pagePanel.add(columnLabel);
        columnLabel.setBounds(580, 150, 190, 410);

        columnHeadline.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        columnHeadline.setForeground(new java.awt.Color(0, 0, 1));
        columnHeadline.setText("Scandalous!");
        columnHeadline.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pagePanel.add(columnHeadline);
        columnHeadline.setBounds(580, 110, 170, 30);

        priceLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(0, 0, 1));
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        priceLabel.setText("Only 0.1 Cr!");
        pagePanel.add(priceLabel);
        priceLabel.setBounds(550, 80, 200, 20);

        news2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        news2.setForeground(new java.awt.Color(0, 0, 1));
        news2.setText("jLabel1");
        news2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pagePanel.add(news2);
        news2.setBounds(390, 150, 180, 180);

        headline2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        headline2.setForeground(new java.awt.Color(0, 0, 1));
        headline2.setText("Headline");
        headline2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pagePanel.add(headline2);
        headline2.setBounds(390, 110, 180, 30);

        leadNewsHeadline.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        leadNewsHeadline.setForeground(new java.awt.Color(0, 0, 1));
        leadNewsHeadline.setText("Lead News Headline");
        leadNewsHeadline.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pagePanel.add(leadNewsHeadline);
        leadNewsHeadline.setBounds(10, 110, 370, 30);

        headline3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        headline3.setForeground(new java.awt.Color(0, 0, 1));
        headline3.setText("Headline");
        headline3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pagePanel.add(headline3);
        headline3.setBounds(10, 340, 180, 30);

        news3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        news3.setForeground(new java.awt.Color(0, 0, 1));
        news3.setText("jLabel1");
        news3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pagePanel.add(news3);
        news3.setBounds(10, 380, 180, 180);

        headline4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        headline4.setForeground(new java.awt.Color(0, 0, 1));
        headline4.setText("Headline");
        headline4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pagePanel.add(headline4);
        headline4.setBounds(200, 340, 180, 30);

        headline5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        headline5.setForeground(new java.awt.Color(0, 0, 1));
        headline5.setText("Headline");
        headline5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pagePanel.add(headline5);
        headline5.setBounds(390, 340, 180, 30);

        news4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        news4.setForeground(new java.awt.Color(0, 0, 1));
        news4.setText("Text");
        news4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pagePanel.add(news4);
        news4.setBounds(200, 380, 180, 180);

        news5.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        news5.setForeground(new java.awt.Color(0, 0, 1));
        news5.setText("Text");
        news5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pagePanel.add(news5);
        news5.setBounds(390, 380, 180, 180);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 1));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("News for the curious");
        pagePanel.add(jLabel4);
        jLabel4.setBounds(240, 80, 280, 20);

        dateTimeLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        dateTimeLabel.setForeground(new java.awt.Color(0, 0, 1));
        dateTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dateTimeLabel.setText("timedate");
        pagePanel.add(dateTimeLabel);
        dateTimeLabel.setBounds(10, 80, 210, 20);

        jScrollPane1.setViewportView(pagePanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel columnHeadline;
    private javax.swing.JLabel columnLabel;
    private javax.swing.JLabel dateTimeLabel;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel headline2;
    private javax.swing.JLabel headline3;
    private javax.swing.JLabel headline4;
    private javax.swing.JLabel headline5;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leadNewsHeadline;
    private javax.swing.JLabel leadNewsLabel;
    private javax.swing.JLabel news2;
    private javax.swing.JLabel news3;
    private javax.swing.JLabel news4;
    private javax.swing.JLabel news5;
    private javax.swing.JPanel pagePanel;
    private javax.swing.JLabel priceLabel;
    // End of variables declaration//GEN-END:variables


    
    public void createRandomEquipmentAd(int index)
    {
        // index should be news 2 ... 5
        
        // try equipement ads
        EquipmentFactory equipmentFactory = new EquipmentFactory();
        EquipmentFactory.Component [] components = EquipmentFactory.Component.values();
        EquipmentFactory.Component component = RandomHelper.oneOf(components);
        ShipComponent shipComponent = equipmentFactory.create(component);
        
        String headline = "Buy now!";
        String base = shipComponent.getName();
        base = base.replace("<", "&lt;");
        base = base.replace(">", "&gt;");
        
        
        String text =
                "<html>The unsurpassed " + base + " is now better than ever!"
                + " Visit your local ship component shop for more details."
                + "</html>";
     
        
        setHeadline(index, headline);
        setNews(index, text);
    }        
        
    public void createRandomTravelAd(int index, Galaxy galaxy, SystemLocation loca)
    {
        // index should be news 2 ... 5
        // try travel ads
                
        String headline = "Visit us!";
        
        final List <Solar> settlements = galaxy.findSettlements(2, loca);
      
        Solar settlement = RandomHelper.oneOf(settlements);
        final Solar root = settlement.root();
        final String name = root.baseName;
        
        String text =
                "<html>Come to visit " + settlement.name + " in system " + name
                + ", the nicest place you"
                + " can find in the local area. We've got the best places to stay and"
                + " quite unique sights."
                + "</html>";
        
        setHeadline(index, headline);
        setNews(index, text);
     }
    
            
}
