/*
 * ProspectorsAgencyPanel.java
 *
 * Created: 23.04.2010
 *
 * Author: Hj. Malthaner
 * Email:  h_malthaner@users.sourceforge.net
 *
 * See license.txt for license details
 */

package solarex.ui.panels;

import java.awt.Container;
import solarex.system.Solar;
import solarex.ui.ComponentFactory;
import solarex.ui.FontFactory;

/**
 *
 * @author Hj. Malthaner
 */
public class ProspectorsAgencyPanel extends javax.swing.JPanel
{

    private SpaceStationPanel spaceStationPanel;

    /** Creates new form ProspectorsAgencyPanel */
    public ProspectorsAgencyPanel(Solar station, SpaceStationPanel spaceStationPanel)
    {
        this.spaceStationPanel = spaceStationPanel;
        
        initComponents();

        titleLabel.setText(station.name + " Prospectors Agency");
        titleLabel.setFont(FontFactory.getPanelHeading());

        jLabel1.setFont(FontFactory.getLabelHeading());
        
        ComponentFactory.customizeButton(loungeButton);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        loungeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(java.awt.Color.black);
        setForeground(java.awt.Color.green);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        contentPanel.setBackground(new java.awt.Color(0, 51, 51));
        contentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.darkGray));
        contentPanel.setForeground(java.awt.Color.green);
        contentPanel.setMinimumSize(new java.awt.Dimension(800, 540));
        contentPanel.setPreferredSize(new java.awt.Dimension(800, 540));
        contentPanel.setLayout(null);

        titleLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        titleLabel.setForeground(java.awt.Color.white);
        titleLabel.setText("XYZ Prospectors Agency");
        contentPanel.add(titleLabel);
        titleLabel.setBounds(20, 10, 420, 40);

        loungeButton.setText("Return To Lounge");
        loungeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loungeButtonActionPerformed(evt);
            }
        });
        contentPanel.add(loungeButton);
        loungeButton.setBounds(20, 500, 170, 25);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel1.setForeground(java.awt.Color.green);
        jLabel1.setText("<html>The prospectors agency is currently closed.</html>");
        contentPanel.add(jLabel1);
        jLabel1.setBounds(280, 180, 270, 200);

        add(contentPanel, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void loungeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loungeButtonActionPerformed
        Container c = getParent();
        c.remove(this);
        c.add(spaceStationPanel);
        c.validate();
        c.repaint();
}//GEN-LAST:event_loungeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loungeButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

}
