/*
 * SetupPanel.java
 *
 * Created: 05.05.2010
 *
 * Author: Hj. Malthaner
 * Email:  h_malthaner@users.sourceforge.net
 *
 * See license.txt for license details
 */

package solarex.ui.panels;

import javax.swing.JOptionPane;
import solarex.io.GameUiSettings;
import solarex.ui.ApplicationFrame;
import solarex.ui.ComponentFactory;
import solarex.ui.FontFactory;

/**
 * Loading and saving games, also general setup options go here.
 * 
 * @author Hj. Malthaner
 */
public class SetupPanel extends javax.swing.JPanel
{

    private ApplicationFrame appFrame;

    public void setSeed(long seed)
    {
        seedField.setText("" + seed);
    }

    /** Creates new form SetupPanel */
    public SetupPanel(ApplicationFrame appFrame)
    {
        this.appFrame = appFrame;
        initComponents();

        jLabel1.setFont(FontFactory.getLarger());
        explorerCheck.setFont(FontFactory.getLarger());
        
        jLabel2.setFont(FontFactory.getPanelHeading());
        jLabel3.setFont(FontFactory.getPanelHeading());
        jLabel4.setFont(FontFactory.getPanelHeading());
        jLabel5.setFont(FontFactory.getPanelHeading());
        
        seedField.setBackground(ComponentFactory.boxBackground);
        
        ComponentFactory.customizeButton(createSystemButton);
        ComponentFactory.customizeButton(loadButton);
        ComponentFactory.customizeButton(randomSystemButton);
        ComponentFactory.customizeButton(saveButton);
        
        explorerCheck.setSelected(true);
        
        if("futuruka.ttf".equals(GameUiSettings.fontName))
        {
            jComboBox1.setSelectedIndex(0);
        }
        if("DidactGothic.ttf".equals(GameUiSettings.fontName))
        {
            jComboBox1.setSelectedIndex(1);
        }
        
        if("Gen-Light 5.ttf".equals(GameUiSettings.fontName))
        {
            jComboBox1.setSelectedIndex(2);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        loadButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        randomSystemButton = new javax.swing.JButton();
        createSystemButton = new javax.swing.JButton();
        seedField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        explorerCheck = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(java.awt.Color.black);
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        contentPanel.setBackground(new java.awt.Color(50, 0, 38));
        contentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.darkGray));
        contentPanel.setMinimumSize(new java.awt.Dimension(800, 540));
        contentPanel.setPreferredSize(new java.awt.Dimension(800, 540));
        contentPanel.setLayout(null);

        loadButton.setBackground(java.awt.Color.gray);
        loadButton.setText("Load Game");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });
        contentPanel.add(loadButton);
        loadButton.setBounds(30, 160, 120, 30);

        saveButton.setBackground(java.awt.Color.gray);
        saveButton.setText("Save Game");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        contentPanel.add(saveButton);
        saveButton.setBounds(30, 120, 120, 30);

        randomSystemButton.setBackground(java.awt.Color.gray);
        randomSystemButton.setText("Create Random System");
        randomSystemButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        randomSystemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomSystemButtonActionPerformed(evt);
            }
        });
        contentPanel.add(randomSystemButton);
        randomSystemButton.setBounds(320, 120, 220, 30);

        createSystemButton.setBackground(java.awt.Color.gray);
        createSystemButton.setText("Create System by Seed");
        createSystemButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        createSystemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSystemButtonActionPerformed(evt);
            }
        });
        contentPanel.add(createSystemButton);
        createSystemButton.setBounds(320, 160, 220, 30);

        seedField.setBackground(java.awt.Color.darkGray);
        seedField.setForeground(java.awt.Color.lightGray);
        seedField.setText("jTextField1");
        seedField.setCaretColor(java.awt.Color.orange);
        seedField.setMargin(new java.awt.Insets(2, 4, 2, 2));
        seedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seedFieldActionPerformed(evt);
            }
        });
        contentPanel.add(seedField);
        seedField.setBounds(560, 160, 180, 30);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel1.setForeground(java.awt.Color.cyan);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("<html>Font changes will only take full effekt after a program restart.</html>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        contentPanel.add(jLabel1);
        jLabel1.setBounds(30, 300, 290, 40);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("UI Settings");
        contentPanel.add(jLabel2);
        jLabel2.setBounds(30, 220, 260, 30);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Create Stellar Systems By Seed");
        contentPanel.add(jLabel3);
        jLabel3.setBounds(320, 60, 360, 30);

        explorerCheck.setForeground(java.awt.Color.green);
        explorerCheck.setText(" Explorer Mode");
        explorerCheck.setOpaque(false);
        explorerCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explorerCheckActionPerformed(evt);
            }
        });
        contentPanel.add(explorerCheck);
        explorerCheck.setBounds(320, 260, 170, 25);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Game Mode");
        contentPanel.add(jLabel4);
        jLabel4.setBounds(320, 220, 270, 30);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Load And Save Games");
        contentPanel.add(jLabel5);
        jLabel5.setBounds(30, 60, 260, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Space Standard", "Didact Gothic", "Gen Light" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        contentPanel.add(jComboBox1);
        jComboBox1.setBounds(90, 262, 120, 30);

        jLabel6.setForeground(new java.awt.Color(0, 255, 0));
        jLabel6.setText("Font:");
        contentPanel.add(jLabel6);
        jLabel6.setBounds(30, 270, 110, 16);

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jLabel7.setForeground(java.awt.Color.cyan);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("<html>Uncheck this to access all system info.<br>\nIf checked, you can only inspect data<br>\nfor systems which you have explored<br>\nalready, or which are generally known.</html>");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        contentPanel.add(jLabel7);
        jLabel7.setBounds(500, 260, 280, 90);

        add(contentPanel, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void seedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seedFieldActionPerformed
        long seed = System.currentTimeMillis();

        try {
            seed = Long.parseLong(seedField.getText());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        appFrame.makeSystem(seed);
    }//GEN-LAST:event_seedFieldActionPerformed

    private void createSystemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSystemButtonActionPerformed
        long seed = System.currentTimeMillis();

        try {
            seed = Long.parseLong(seedField.getText());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        appFrame.makeSystem(seed);
    }//GEN-LAST:event_createSystemButtonActionPerformed

    private void randomSystemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomSystemButtonActionPerformed

        long seed = System.currentTimeMillis();
        setSeed(seed);
        appFrame.makeSystem(seed);

    }//GEN-LAST:event_randomSystemButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        boolean ok = appFrame.saveGame();

        if(ok) {
            JOptionPane.showMessageDialog(this, "Game saved sucessfully.");
        } else {
            JOptionPane.showMessageDialog(this, "Error while saving game.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        boolean ok = appFrame.loadGame();

        if(ok) {
            JOptionPane.showMessageDialog(appFrame, "Game loaded sucessfully.");
        } else {
            JOptionPane.showMessageDialog(appFrame, "Error while loading game.", "Error", JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_loadButtonActionPerformed

    private void explorerCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explorerCheckActionPerformed
        appFrame.setExplorerMode(explorerCheck.isSelected());
    }//GEN-LAST:event_explorerCheckActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        int index = jComboBox1.getSelectedIndex();
        
        if(index == 1)
        {
            // didact gothic 
            GameUiSettings.fontName = "DidactGothic.ttf";
        }
        else if(index == 2)
        {
            // didact gothic 
            GameUiSettings.fontName = "Gen-Light 5.ttf";
        }
        else
        {
            // space standard
            GameUiSettings.fontName = "futuruka.ttf";
        }
        
        GameUiSettings.save();        
    }//GEN-LAST:event_jComboBox1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton createSystemButton;
    private javax.swing.JCheckBox explorerCheck;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton randomSystemButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField seedField;
    // End of variables declaration//GEN-END:variables

}
