/*
 * ShipyardPanel.java
 *
 * Created: 23.04.2010
 *
 * Author: Hj. Malthaner
 * Email:  h_malthaner@users.sourceforge.net
 *
 * See license.txt for license details
 */

package solarex.ui.panels;

import java.awt.Container;
import java.text.NumberFormat;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import solarex.ship.Ship;
import solarex.ship.ShipType;
import solarex.system.Solar;
import solarex.ui.ComponentFactory;
import solarex.ui.FontFactory;

/**
 *
 * @author Hj. Malthaner
 */
public class ShipyardPanel extends javax.swing.JPanel
{
    private Ship ship;
    private SpaceStationPanel spaceStationPanel;

    /** Creates new form ShipyardPanel */
    public ShipyardPanel(Ship ship, Solar station, SpaceStationPanel spaceStationPanel)
    {
        this.ship = ship;
        this.spaceStationPanel = spaceStationPanel;
        
        initComponents();
        initShipList();
        
        titleLabel.setText(station.name + " Shipyard");
        titleLabel.setFont(FontFactory.getPanelHeading());
        
        serviceLabel.setFont(FontFactory.getPanelHeading());
        
        shipsLabel.setFont(FontFactory.getLabelHeading());
        detailsLabel.setFont(FontFactory.getLabelHeading());
        tradeLabel.setFont(FontFactory.getLabelHeading());
        
        detailsField.setFont(FontFactory.getLarger());
        detailsField.setBackground(ComponentFactory.boxBackground);
        
        jLabel4.setFont(FontFactory.getLarger());
        jLabel6.setFont(FontFactory.getLarger());
        jLabel10.setFont(FontFactory.getLarger());
        jLabel11.setFont(FontFactory.getLarger());
        jLabel13.setFont(FontFactory.getLarger());
        jLabel14.setFont(FontFactory.getLarger());
        
        jLabel2.setFont(FontFactory.getLabelHeading());
        jLabel5.setFont(FontFactory.getLabelHeading());

        cashField.setFont(FontFactory.getLarger());
        newShipPriceField.setFont(FontFactory.getLarger());
        oldShipPriceField.setFont(FontFactory.getLarger());
        totalPriceField.setFont(FontFactory.getLarger());
        
        ComponentFactory.customizeScrollpane(jScrollPane1);
        ComponentFactory.customizeButton(loungeButton);

        
        ComponentFactory.customizeButton(jButton1);
        ComponentFactory.customizeButton(jButton2);
        ComponentFactory.customizeButton(jButton3);
        ComponentFactory.customizeButton(jButton4);
        ComponentFactory.customizeButton(jButton5);
        ComponentFactory.customizeButton(jButton6);
        ComponentFactory.customizeButton(buyShipButton);
        ComponentFactory.customizeButton(jButton8);
        ComponentFactory.customizeButton(jButton9);

        jButton1.setFont(FontFactory.getNormal());
        jButton2.setFont(FontFactory.getNormal());
        jButton3.setFont(FontFactory.getNormal());
        jButton4.setFont(FontFactory.getNormal());
        jButton5.setFont(FontFactory.getNormal());
        jButton6.setFont(FontFactory.getNormal());
        jButton8.setFont(FontFactory.getNormal());
        jButton9.setFont(FontFactory.getNormal());
        
        
        ComponentFactory.customizeList(shipList, 1);

        shipListValueChanged(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        loungeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totalPriceField = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        shipList = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        serviceLabel = new javax.swing.JLabel();
        shipsLabel = new javax.swing.JLabel();
        buyShipButton = new javax.swing.JButton();
        detailsLabel = new javax.swing.JLabel();
        tradeLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cashField = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        newShipPriceField = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        detailsField = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        oldShipPriceField = new javax.swing.JLabel();

        setBackground(java.awt.Color.black);
        setForeground(java.awt.Color.green);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.GridBagLayout());

        contentPanel.setBackground(new java.awt.Color(0, 51, 51));
        contentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.darkGray));
        contentPanel.setForeground(java.awt.Color.green);
        contentPanel.setMinimumSize(new java.awt.Dimension(800, 540));
        contentPanel.setPreferredSize(new java.awt.Dimension(800, 540));
        contentPanel.setLayout(null);

        titleLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        titleLabel.setForeground(java.awt.Color.white);
        titleLabel.setText("XYZ Shipyard");
        contentPanel.add(titleLabel);
        titleLabel.setBounds(20, 10, 420, 40);

        loungeButton.setText("Return To Lounge");
        loungeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loungeButtonActionPerformed(evt);
            }
        });
        contentPanel.add(loungeButton);
        loungeButton.setBounds(20, 500, 160, 25);

        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("High catalyst fusion fuel:");
        contentPanel.add(jLabel2);
        jLabel2.setBounds(20, 440, 190, 20);

        totalPriceField.setForeground(new java.awt.Color(255, 255, 255));
        totalPriceField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalPriceField.setText("0Cr");
        contentPanel.add(totalPriceField);
        totalPriceField.setBounds(670, 210, 90, 40);

        jButton1.setText("10.0t");
        jButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        contentPanel.add(jButton1);
        jButton1.setBounds(470, 440, 70, 20);

        jButton2.setText("0.1t");
        jButton2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        contentPanel.add(jButton2);
        jButton2.setBounds(310, 440, 70, 20);

        jButton3.setText("1.0t");
        jButton3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        contentPanel.add(jButton3);
        jButton3.setBounds(390, 440, 70, 20);

        jButton4.setText("0.1t");
        jButton4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        contentPanel.add(jButton4);
        jButton4.setBounds(310, 410, 70, 20);

        jButton5.setText("1.0t");
        jButton5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        contentPanel.add(jButton5);
        jButton5.setBounds(390, 410, 70, 20);

        jButton6.setText("Full");
        jButton6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        contentPanel.add(jButton6);
        jButton6.setBounds(550, 440, 80, 20);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 128, 128)));

        shipList.setBackground(new java.awt.Color(64, 64, 64));
        shipList.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        shipList.setForeground(new java.awt.Color(192, 192, 192));
        shipList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Space Bug (Used)", "Locust Harvester (Heavily Used)", "Deep Space Clipper (New)" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        shipList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                shipListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(shipList);

        contentPanel.add(jScrollPane1);
        jScrollPane1.setBounds(20, 90, 200, 250);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("0.0/1.0t");
        contentPanel.add(jLabel4);
        jLabel4.setBounds(200, 440, 90, 20);

        serviceLabel.setForeground(new java.awt.Color(255, 255, 255));
        serviceLabel.setText("Gas Station Services");
        contentPanel.add(serviceLabel);
        serviceLabel.setBounds(20, 370, 330, 20);

        shipsLabel.setForeground(new java.awt.Color(0, 255, 0));
        shipsLabel.setText("Available Ships");
        contentPanel.add(shipsLabel);
        shipsLabel.setBounds(20, 60, 170, 20);

        buyShipButton.setText("Buy Ship");
        buyShipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyShipButtonActionPerformed(evt);
            }
        });
        contentPanel.add(buyShipButton);
        buyShipButton.setBounds(550, 310, 220, 25);

        detailsLabel.setForeground(new java.awt.Color(0, 255, 0));
        detailsLabel.setText("Ship Details");
        contentPanel.add(detailsLabel);
        detailsLabel.setBounds(240, 60, 170, 20);

        tradeLabel.setForeground(new java.awt.Color(0, 255, 0));
        tradeLabel.setText("Trade Details");
        contentPanel.add(tradeLabel);
        tradeLabel.setBounds(550, 60, 170, 20);

        jLabel10.setForeground(new java.awt.Color(255, 200, 0));
        jLabel10.setText("Old ship refund:");
        contentPanel.add(jLabel10);
        jLabel10.setBounds(550, 180, 120, 20);

        jLabel11.setForeground(new java.awt.Color(255, 200, 0));
        jLabel11.setText("Total Price:");
        contentPanel.add(jLabel11);
        jLabel11.setBounds(550, 210, 120, 40);

        cashField.setForeground(new java.awt.Color(255, 255, 255));
        cashField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cashField.setText("100000Cr");
        contentPanel.add(cashField);
        cashField.setBounds(670, 100, 90, 20);

        jLabel13.setForeground(new java.awt.Color(255, 200, 0));
        jLabel13.setText("Cash:");
        contentPanel.add(jLabel13);
        jLabel13.setBounds(550, 100, 120, 20);

        newShipPriceField.setForeground(new java.awt.Color(255, 255, 255));
        newShipPriceField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        newShipPriceField.setText("100000Cr");
        contentPanel.add(newShipPriceField);
        newShipPriceField.setBounds(670, 160, 90, 20);
        contentPanel.add(jSeparator1);
        jSeparator1.setBounds(540, 210, 230, 10);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 128, 128)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        detailsField.setBackground(new java.awt.Color(64, 64, 64));
        detailsField.setForeground(new java.awt.Color(192, 192, 192));
        detailsField.setText("No Ship Selected");
        detailsField.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        detailsField.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        detailsField.setOpaque(true);
        jPanel1.add(detailsField, java.awt.BorderLayout.CENTER);

        contentPanel.add(jPanel1);
        jPanel1.setBounds(240, 90, 290, 250);

        jButton8.setText("10.0t");
        jButton8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        contentPanel.add(jButton8);
        jButton8.setBounds(470, 410, 70, 20);

        jButton9.setText("Full");
        jButton9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        contentPanel.add(jButton9);
        jButton9.setBounds(550, 410, 80, 20);

        jLabel5.setForeground(new java.awt.Color(0, 255, 0));
        jLabel5.setText("Low catalyst fusion fuel:");
        contentPanel.add(jLabel5);
        jLabel5.setBounds(20, 410, 190, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("0.0/1.0t");
        jLabel6.setToolTipText("");
        contentPanel.add(jLabel6);
        jLabel6.setBounds(200, 410, 90, 20);

        jLabel14.setForeground(new java.awt.Color(255, 200, 0));
        jLabel14.setText("Ship Price:");
        contentPanel.add(jLabel14);
        jLabel14.setBounds(550, 160, 120, 20);

        oldShipPriceField.setForeground(new java.awt.Color(255, 255, 255));
        oldShipPriceField.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        oldShipPriceField.setText("100000Cr");
        contentPanel.add(oldShipPriceField);
        oldShipPriceField.setBounds(670, 180, 90, 20);

        add(contentPanel, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void loungeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loungeButtonActionPerformed
        Container c = getParent();
        c.remove(this);
        c.add(spaceStationPanel);
        c.validate();
        c.repaint();
}//GEN-LAST:event_loungeButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void buyShipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyShipButtonActionPerformed
        Object o = shipList.getSelectedValue();
        
        if(o != null)
        {
            ShipType type = (ShipType)o;
            ship.cargo.money += (ship.type.price - type.price);
            ship.setType(type);
            
            SwingUtilities.invokeLater(
                    new Runnable()
                    {
                        @Override
                        public void run()
                        {
                            shipList.setSelectedValue(null, false);
                        }
                    });
        }
        
        NumberFormat nf = NumberFormat.getNumberInstance();
        nf.setMinimumFractionDigits(2);
        nf.setMaximumFractionDigits(2);

        cashField.setText(nf.format(ship.cargo.money) + " Cr");
    }//GEN-LAST:event_buyShipButtonActionPerformed

    private void shipListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_shipListValueChanged
        NumberFormat nf = NumberFormat.getNumberInstance();
        nf.setMinimumFractionDigits(2);
        nf.setMaximumFractionDigits(2);

        Object o = shipList.getSelectedValue();

        if(o != null)
        {
            ShipType type = (ShipType)o;
            
            oldShipPriceField.setText("-" + nf.format(ship.type.price) + " Cr");
            newShipPriceField.setText("" + nf.format(type.price) + " Cr");
            totalPriceField.setText("" + nf.format(type.price - ship.type.price) + " Cr");
            
            detailsField.setText("<html>" +   
                    "Total Weight: <font color='#FFFFFF'>" + type.totalMass + "</font><br>" + 
                    "Equip. Space: <font color='#FFFFFF'>" + type.equipmentSpace + "</font><br>" + 
                    "Price: <font color='#FFFFFF'>" + nf.format(type.price) + " Cr</font><br><br>" +
                    type.shipDesc + 
                    "</html>");
        }
        else
        {
            oldShipPriceField.setText("-");
            newShipPriceField.setText("-");
            totalPriceField.setText("-");
            detailsField.setText("No ship selected.");
        }

        cashField.setText(nf.format(ship.cargo.money) + " Cr");
    }//GEN-LAST:event_shipListValueChanged

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyShipButton;
    private javax.swing.JLabel cashField;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel detailsField;
    private javax.swing.JLabel detailsLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loungeButton;
    private javax.swing.JLabel newShipPriceField;
    private javax.swing.JLabel oldShipPriceField;
    private javax.swing.JLabel serviceLabel;
    private javax.swing.JList shipList;
    private javax.swing.JLabel shipsLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel totalPriceField;
    private javax.swing.JLabel tradeLabel;
    // End of variables declaration//GEN-END:variables

    private void initShipList() 
    {
        DefaultListModel model = new DefaultListModel();
        
        model.addElement(ShipType.COURIER);
        model.addElement(ShipType.SPACE_BUG);
        model.addElement(ShipType.LOCUST_HARVESTER);
        model.addElement(ShipType.DEEP_SPACE_CLIPPER);
        
        shipList.setModel(model);
    }
}
